### ISSUE TITLE
[BugFix] [RHEL/6] One instance of "When evaluating an <xccdf:check-content-ref> element within an <xccdf:check> element, its @href attribute either MUST contain a "#" + @id of a <ds:component-ref> element or MUST be resolved in the context of the XML Catalog specified as part of the <ds:component-ref> element that is referencing this benchmark. " error

### ISSUE THREAD

**Issue by iankko** [OpenSCAP/scap-security-guide#1088] opened 2016-03-18 13:20 UTC
When evaluation current RHEL-6 USGCB SSG content against SCAP NIST content validation testsuite on 2016-03-18 (https://jlieskov.fedorapeople.org/2016-03-18-scap-validation-result.html) there's one instance of the following error:
```
31-1 	1(of 1)

ERROR 	SCHEMATRON

scap_org.open-scap_datastream_from_xccdf_ssg-rhel6-xccdf-1.2.xml - When
evaluating an <xccdf:check-content-ref> element within an <xccdf:check> element,
its @href attribute either MUST contain a "#" + @id of a <ds:component-ref> element
or MUST be resolved in the context of the XML Catalog specified as part of the
<ds:component-ref> element that is referencing this benchmark. In either case,
the @href attribute MUST ultimately resolve to a <ds:component-ref> element
in the data stream referencing the benchmark containing this <xccdf:check-content-ref> 
element. See Section 3.1.1 for additional information on <ds:component-ref> resolution. 	

xccdf:Rule xccdf_org.ssgproject.content_rule_security_patches_up_to_date in ds:data-stream 
scap_org.open-scap_datastream_from_xccdf_ssg-rhel6-xccdf-1.2.xml

Schematron Context:
/*:data-stream-collection[namespace-uri()='http://scap.nist.gov/schema/scap/source/1.2'][1]/*:data-
stream[namespace-uri()='http://scap.nist.gov/schema/scap/source/1.2'][1] 	every $m in 
ds:checklists/ds:component-ref satisfies every $n in xcf:get-component($m)//xccdf:Rule
//xccdf:check-content-ref satisfies exists(xcf:get-component-ref($m/cat:catalog, $n/@href)) 
```

**Comment by iankko** [comment] 2016-03-21 15:25
Moving back to the pool so others can have a look too.

**Comment by mpreisler** [comment] 2016-03-21 15:35
Looks like an issue in the schematron / test-suite to me. The URL is a remote URL for the OVAL feed.

Assigning to myself, will report to scap-dev soon.

**Comment by mpreisler** [comment] 2016-03-22 15:37
Dragos confirmed that this is a bug in SCAPVal in an email to scap-dev. I believe we can close this ticket.

> Hello Mr. Preisler,
>
>   Thank you for bringing this issue to our attention. You’re correct; currently SCAPVal does not support external references. We’ve identified this issue a while back and implemented basic support for external references (the tool will display a warning instead of an error when the content includes external references), but I’ve created a ticket to track your proposal.
>
>   We appreciate your email and look forward to the opportunity to provide additional support if needed.
>
> Respectfully,
> Dragos Prisaca 
>  NVLAP Technical Expert
>  NIST SCAP Validation Program | NIST ITL/CSD support

**Closed by mpreisler** 2016-03-22 15:37 UTC
Labels: bugfix, help wanted, RHEL6

**Comment by iankko** [comment] 2016-04-01 11:18
The ```scap-security-guide-nist-testsuite``` Jenkins testing job has been instructed to whitelist the specific error message for this error:
```
ERROR: SCHEMATRON - [ssg-rhel6-ds.xml] scap_org.open-scap_datastream_from
xccdf_ssg-rhel6-xccdf-1.2.xml - When evaluating an <xccdf:check-content-ref>
element within an <xccdf:check> element, its @href attribute either MUST
contain a "#" + @id of a <ds:component-ref> element or MUST be resolved
in the context of the XML Catalog specified as part of the <ds:component-ref>
element that is referencing this benchmark. In either case, the @href attribute
MUST ultimately resolve to a <ds:component-ref> element in the data stream
referencing the benchmark containing this <xccdf:check-content-ref> element.
See Section 3.1.1 for additional information on <ds:component-ref> resolution.
```
Since like Martin pointed out above the issue isn't in SSG content, but rather in SCAP NIST testsuite itself (future ScapVal version should fix that).
